### ISSUE TITLE
Carpeta dist

### ISSUE THREAD

**Issue by Epotignano** [Epotignano/jhipster-angular#9]
Donde quieren que genere la carpeta con el /dist con la app minificada? Actualmente se genera en webapp/dist, pero la quieren en otro lado? 

Hoy tambien se esta poniendo en webapp la app sin minificar para que sea posible para ustedes debuggear, pero si quieren, lo saco y dejo webapp como dist, decidan ustedes @fernandodanielgarcia

**Comment by fernandodanielgarcia** [comment]
1) En webapp/dist está OK
2) En webapp OK

**Comment by Epotignano** [comment]
@fernandodanielgarcia

**Comment by fernandodanielgarcia** [comment]
Dejemoslo como está ahora, que el build lo mande a webapp/serve.
Para que ande hay que mover el contenido de la carpeta serve a webapp.
Luego vamos a modificar el gulp para que lo mande a la carpeta que corresponde que sería en principio: src/main/resources/static
